### ISSUE TITLE
latest release 3.5.21 - Drop Down Menus moved to the left

### ISSUE THREAD

**Issue by southpaw3229** [templaza/jollyany-framework#20]
After installing the latest jollyany-frame work version 3.5.21, I noticed all my dropdown main menu items are moved to the left and not under the appropriate parent menu item.

The only other update I ran was Astroid Framework 3.0.8 which I am also going to bring to their attention.

I am running Joomla 4.4.1 / php 8.2

Thanks
![dropdown-menu-issue](https://github.com/templaza/jollyany-framework/assets/6591120/21fe59c1-b50f-4de2-9aed-b7a3b6ff735d)

**Comment by southpaw3229** [comment]
Thanks for quick reply.  Is this in regular joomla backend under Menu Manager as I don't see it.  Or is this in the template settings, which mine is really powered by Astroid Framework.

**Comment by southpaw3229** [comment]
Any update on this?  do you think this will get resolved in next release?  Thanks

**Comment by sonvnn** [comment]
![Screen Shot 2024-01-05 at 08 09 54](https://github.com/templaza/jollyany-framework/assets/3204103/c8157c62-fda9-4400-9b84-144c3540e0aa)
Just edit Menu Item and you can see it here. If you can not find it please send me your admin account. I will help you check it.

Thanks & Best regards,
Sonny

**Comment by southpaw3229** [comment]
Ok Thanks.  What's weird is when I select Left it actually moves to the right where it should be.  This will work, but wanted to let you know.

Thanks

**Comment by sonvnn** [comment]
Thanks! I will close this issue.
